In [2]:
import caffe
import numpy as np
from caffe import layers as L,params as P,proto,to_proto
from caffe import Net
import sys

In [3]:
root='/home/sdu/caffe-ssd/'                                              #根目录
deploy=root + 'models/VGGNet/VOC0712/SSD_300x300zl/deploy.prototxt'                   #deploy文件
                 #deploy文件
 #训练好的 caffemodel
caffe_model=root + 'models/VGGNet/VOC0712/SSD_300x300zl/VGG_VOC0712_SSD_300x300_iter_120000.caffemodel' 

In [4]:
net = caffe.Net(deploy,caffe_model, 0)
print net

In [5]:
[(k,v[0].data.shape) for k,v in net.params.items()]  #查看各层参数规模

[('conv1_1', (64, 3, 3, 3)),
 ('conv1_2', (64, 64, 3, 3)),
 ('conv2_1', (128, 64, 3, 3)),
 ('conv2_2', (128, 128, 3, 3)),
 ('conv3_1', (256, 128, 3, 3)),
 ('conv3_2', (256, 256, 3, 3)),
 ('conv3_3', (256, 256, 3, 3)),
 ('conv4_1', (512, 256, 3, 3)),
 ('conv4_2', (512, 512, 3, 3)),
 ('conv4_3', (512, 512, 3, 3)),
 ('conv5_1', (512, 512, 3, 3)),
 ('conv5_2', (512, 512, 3, 3)),
 ('conv5_3', (512, 512, 3, 3)),
 ('fc6', (1024, 512, 3, 3)),
 ('fc7', (1024, 1024, 1, 1)),
 ('conv6_1', (256, 1024, 1, 1)),
 ('conv6_2', (512, 256, 3, 3)),
 ('conv7_1', (128, 512, 1, 1)),
 ('conv7_2', (256, 128, 3, 3)),
 ('conv8_1', (128, 256, 1, 1)),
 ('conv8_2', (256, 128, 3, 3)),
 ('conv9_1', (128, 256, 1, 1)),
 ('conv9_2', (256, 128, 3, 3)),
 ('conv4_3_norm', (512,)),
 ('conv4_3_norm_mbox_loc', (16, 512, 3, 3)),
 ('conv4_3_norm_mbox_conf', (84, 512, 3, 3)),
 ('fc7_mbox_loc', (24, 1024, 3, 3)),
 ('fc7_mbox_conf', (126, 1024, 3, 3)),
 ('conv6_2_mbox_loc', (24, 512, 3, 3)),
 ('conv6_2_mbox_conf', (126, 512, 3, 3))

In [6]:
a=net.params['conv1_1'][0].data    #提取conv1的参数
print a 

[[[[  3.39540511e-01   3.71203840e-01  -3.80115025e-02]
   [  2.22264856e-01   4.53896709e-02  -3.44842851e-01]
   [ -4.49809730e-02  -2.30247706e-01  -2.85200685e-01]]

  [[  4.58282560e-01   4.49964076e-01  -7.13862702e-02]
   [  2.91162759e-01   4.83327433e-02  -4.44027662e-01]
   [ -5.03447838e-02  -2.94075549e-01  -4.02535617e-01]]

  [[  4.04896647e-01   4.22994286e-01  -5.63664660e-02]
   [  2.62605071e-01   4.91995029e-02  -4.12687123e-01]
   [ -5.15240096e-02  -2.73497015e-01  -3.70778441e-01]]]


 [[[  1.32622078e-01   1.83417737e-01   1.49063647e-01]
   [  1.57254070e-01   2.18722254e-01   1.65998474e-01]
   [  1.43419236e-01   1.82646394e-01   1.49414405e-01]]

  [[  2.32641976e-02   4.26072218e-02   4.31125164e-02]
   [  2.24064849e-02   5.26164509e-02   3.59666087e-02]
   [  4.01371643e-02   4.83065471e-02   5.06134480e-02]]

  [[ -1.75109342e-01  -1.89479828e-01  -1.55544519e-01]
   [ -2.08188787e-01  -2.12241143e-01  -1.95280477e-01]
   [ -1.63719043e-01  -1.88723415e-0

In [ ]:
for i_n in range(a.shape[0]):
    for i_c in range(a.shape[1]):
        for i_h in range(a.shape[2]):
            for i_w in range(a.shape[3]):
                if abs(net.params['conv1'][0].data[i_n][i_c][i_h][i_w]) < 0.2:   #小于阈值的权值设为0 
                    net.params['conv1'][0].data[i_n][i_c][i_h][i_w]=0'''

In [ ]:
net.save('new.caffemodel')